version: '3.8'

volumes: 
  dbvolume:

services:
  db:
    container_name: postgres_riveria
    image: postgres:16.1
    ports: 
      - 5435:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: measurements
    volumes:
        - ./db/init:/docker-entrypoint-initdb.d
        - dbvolume:/var/lib/postgresql/data
  
  appservnodedocker:
    container_name: appserv_riveria
    build: backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
      # DEBUG: mqttjs*
    ports:
      - 3000:3000
    volumes: 
        - ./backend/server.js:/usr/src/server/server.js
        
  mosquitto:
    container_name: local_mosquitto
    image: eclipse-mosquitto
    depends_on:
      - db
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  vite_docker:
    container_name: vite_riveria
    build: frontend
    ports:
      - 8000:8000
    working_dir: /usr/src/server
    volumes:
      - type: bind
        source: ./frontend/src
        target: /usr/src/server/src