version: '3.4'

volumes: 
  dbvolume:

services:
  appservnodedocker:
    image: appservnodedocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  db:
    image: postgres
    ports: 
      - 5435:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: measurements
    volumes:
        - ./db/init:/docker-entrypoint-initdb.d
        - dbvolume:/var/lib/postgresql/data