version: '3.4'

volumes: 
  dbvolume:

services:
  db:
    container_name: postgres_riveria
    image: postgres:16.1
    ports: 
      - 5435:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: measurements
    volumes:
        - ./backend/db/init:/docker-entrypoint-initdb.d
        - dbvolume:/var/lib/postgresql/data
  
  appservnodedocker:
    container_name: appserv_riveria
    image: appservnodedocker
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: production
      # DEBUG: mqttjs*
    ports:
      - 3000:3000
    volumes: 
        - ./backend/server.js:/usr/src/server/server.js
        
  mosquitto:
    container_name: local_mosquitto
    image: eclipse-mosquitto
    depends_on:
      - db
    ports:
      - 1883:1883
    volumes:
      - ./backend/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf